### ISSUE TITLE
Format function

### ISSUE THREAD

**Issue by rista404** [rista404/deno-debug#1]
I'm currently using a custom `format.ts` ported from https://github.com/defunctzombie/node-util/blob/master/util.js

I didn't port `util.inspect`, instead using `deno.inspect`, and I'm wondering should we port the entire utility function since `debug` utility has a couple of env vars that it passes down to `util.inspect`?

**Comment by rista404** [comment]
Yo @kevinkassimo, not sure what do with this, any advice? 

If we want to be fully compatible with `debug` we want to allow passing `INSPECT_OPTS` that `util.inspect` uses, to control output and have 1:1 formatting output.

**Comment by kevinkassimo** [comment]
I would say just implement a subset for now (I don't think a 100% compatibility is the most important thing at the current stage).
Would be a cool thing if we can port `util.inspect` or improving `deno.inspect` of the core. You could check out `js/console.ts` for details of current implementation.

**Comment by rista404** [comment]
Thanks! Discovered that `deno.inspect` also takes in opts the same shape as `util.inspect` as seen here: https://github.com/denoland/deno/blob/master/js/console.ts#L9-L15 (although it's not using some of it).

I'll try to see the differences between the two inspects and see what I can do to help.
